name: Build TV APK

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build-tv-apk:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Java environment
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      # Setup Flutter environment
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.x'
          cache: true

      # Create dummy key.properties file to avoid build errors
      - name: Create dummy key.properties
        run: |
          echo "storePassword=dummy" > simple_live_tv_app/android/key.properties
          echo "keyPassword=dummy" >> simple_live_tv_app/android/key.properties
          echo "keyAlias=dummy" >> simple_live_tv_app/android/key.properties
          echo "storeFile=/dev/null" >> simple_live_tv_app/android/key.properties

      # Restore Flutter packages for TV app
      - name: Restore TV app packages
        run: |
          cd simple_live_tv_app
          flutter pub get

      # Build TV APK
      - name: Build TV APK
        run: |
          cd simple_live_tv_app
          flutter build apk --release

      # Upload TV APK artifacts
      - name: Upload TV APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tv-app-apk
          path: |
            simple_live_tv_app/build/app/outputs/flutter-apk/app-release.apk