name: Build APK

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Java environment
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      # Setup Flutter environment
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.x'
          cache: true

      # Create a self-signed keystore for development
      - name: Create self-signed keystore
        run: |
          cd simple_live_app/android
          keytool -genkey -v -keystore debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US" -storetype JKS

      # Create key.properties file
      - name: Create key.properties
        run: |
          echo "storePassword=android" > simple_live_app/android/key.properties
          echo "keyPassword=android" >> simple_live_app/android/key.properties
          echo "keyAlias=androiddebugkey" >> simple_live_app/android/key.properties
          echo "storeFile=debug.keystore" >> simple_live_app/android/key.properties

      # Restore Flutter packages
      - name: Restore packages
        run: |
          cd simple_live_app
          flutter pub get

      # Build signed APK
      - name: Build signed APK
        run: |
          cd simple_live_app
          flutter build apk --release --split-per-abi

      # Upload APK artifacts
      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: |
            simple_live_app/build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
            simple_live_app/build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
            simple_live_app/build/app/outputs/flutter-apk/app-x86_64-release.apk